import { useEffect, useMemo, useState } from 'react'
import { Link } from 'react-router-dom'
import { getCausalAudit } from '../lib/data.js'
import { Loading, ErrorBox } from '../components/Loading.jsx'

// Hypothesis roll-up cards + per-feature table for Phase 4 (causal validation).
// Data source: /data/causal_audit.json generated by scripts/05_build_atlas_data.py.

export default function CausalAuditPage() {
  const [audit, setAudit] = useState(null)
  const [error, setError] = useState(null)
  const [search, setSearch] = useState('')
  const [filter, setFilter] = useState('all') // all | graph_dependent | tech_specific | survivors | refuted
  const [sortKey, setSortKey] = useState('dep_self_loop_norm')
  const [limit, setLimit] = useState(100)

  useEffect(() => {
    getCausalAudit().then(setAudit).catch(setError)
  }, [])

  if (error) return <ErrorBox error={error} />
  if (!audit) return <Loading what="causal audit" />

  const hyp = audit.hypotheses || {}
  const rows = audit.per_feature_table || []

  const filteredRows = useMemo(() => {
    let r = rows
    if (search) {
      const q = search.toLowerCase()
      r = r.filter((x) =>
        String(x.feature_idx).includes(q) ||
        (x.label || '').toLowerCase().includes(q) ||
        (x.top_tissue || '').toLowerCase().includes(q) ||
        (x.top_domain_l7 || '').toLowerCase().includes(q)
      )
    }
    if (filter === 'graph_dependent') {
      r = r.filter((x) => (x.dep_self_loop_norm || 0) > 0.5)
    } else if (filter === 'tech_specific') {
      r = r.filter((x) => x.tech_specific === true)
    } else if (filter === 'survivors') {
      r = r.filter((x) => x.survives_all === true)
    } else if (filter === 'causally_active') {
      r = r.filter((x) => (x.proto_reassign_rate || 0) > 0.2)
    }
    const sorted = [...r].sort((a, b) => {
      const av = a[sortKey] ?? -Infinity
      const bv = b[sortKey] ?? -Infinity
      if (av === bv) return a.feature_idx - b.feature_idx
      return bv - av
    })
    return sorted
  }, [rows, search, filter, sortKey])

  const visible = filteredRows.slice(0, limit)

  return (
    <div>
      <div className="text-xs text-slate-500 mb-2">
        <Link to="/" className="hover:text-brand-300">Overview</Link> / Causal audit
      </div>
      <h1 className="text-3xl font-bold text-slate-50 tracking-tight mb-2">
        Causal audit
      </h1>
      <p className="text-slate-400 max-w-3xl leading-relaxed mb-8">
        Phase-4 validation of every aggregator feature against the pre-registered hypotheses.
        Each feature is scored on prototype redundancy (H6), spatial coherence (H7), contextual
        dependency under three graph-ablation regimes (H8), tech specificity (H9), and survival
        under the strict confound suite (H2). The hypothesis cards below summarize
        novae-human-0; the table lets you drill into individual features.
      </p>

      {/* Hypothesis roll-up cards */}
      <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-4 mb-10">
        {Object.entries(hyp).map(([key, h]) => (
          <HypothesisCard key={key} id={key} h={h} />
        ))}
      </div>

      {/* Per-feature table */}
      <h2 className="text-xl font-bold text-slate-100 mb-3">Per-feature causal table</h2>
      <div className="flex flex-wrap items-center gap-3 mb-4">
        <input
          type="text"
          placeholder="search feature_idx, label, tissue, domain..."
          value={search}
          onChange={(e) => setSearch(e.target.value)}
          className="px-3 py-1.5 rounded bg-slate-900 border border-slate-800 text-slate-100 text-xs min-w-[260px]"
        />
        <select
          value={filter}
          onChange={(e) => setFilter(e.target.value)}
          className="px-2 py-1.5 rounded bg-slate-900 border border-slate-800 text-slate-300 text-xs"
        >
          <option value="all">all features</option>
          <option value="graph_dependent">graph-dependent (dep &gt; 0.5)</option>
          <option value="tech_specific">tech-specific</option>
          <option value="survivors">confound survivors</option>
          <option value="causally_active">proto reassign &gt; 20%</option>
        </select>
        <select
          value={sortKey}
          onChange={(e) => setSortKey(e.target.value)}
          className="px-2 py-1.5 rounded bg-slate-900 border border-slate-800 text-slate-300 text-xs"
        >
          <option value="dep_self_loop_norm">sort: dep_self_loop_norm</option>
          <option value="dep_random_rewire">sort: dep_random_rewire</option>
          <option value="morans_i_mean">sort: Moran's I</option>
          <option value="proto_max_abs_cos">sort: proto max|cos|</option>
          <option value="proto_reassign_rate">sort: proto reassign rate</option>
          <option value="l7_reassign_rate">sort: l7 reassign rate</option>
          <option value="tissue_max_ratio">sort: tissue max ratio</option>
          <option value="tech_max_ratio">sort: tech max ratio</option>
          <option value="slide_max_ratio">sort: slide max ratio</option>
          <option value="baseline_l7_top_frac">sort: baseline niche frac</option>
        </select>
        <span className="text-xs text-slate-500">
          {filteredRows.length} / {rows.length} features
        </span>
      </div>

      <div className="overflow-x-auto rounded-lg border border-slate-800 bg-slate-900/40">
        <table className="w-full text-xs">
          <thead className="bg-slate-900 text-slate-400 uppercase text-[10px] tracking-wider">
            <tr>
              <th className="text-left px-2 py-2">feat</th>
              <th className="text-left px-2 py-2">label</th>
              <th className="text-left px-2 py-2">tissue</th>
              <th className="text-left px-2 py-2">l7 niche</th>
              <th className="text-right px-2 py-2">Moran's I</th>
              <th className="text-right px-2 py-2">proto max|cos|</th>
              <th className="text-right px-2 py-2">dep (norm)</th>
              <th className="text-right px-2 py-2">dep (rewire)</th>
              <th className="text-right px-2 py-2">tissue×</th>
              <th className="text-right px-2 py-2">tech×</th>
              <th className="text-right px-2 py-2">slide×</th>
              <th className="text-right px-2 py-2">proto reassign</th>
              <th className="text-right px-2 py-2">l7 reassign</th>
              <th className="text-center px-2 py-2">survives</th>
            </tr>
          </thead>
          <tbody className="divide-y divide-slate-800">
            {visible.map((r) => (
              <tr key={r.feature_idx} className="hover:bg-slate-800/40 transition">
                <td className="px-2 py-1.5 font-mono text-brand-300">
                  <Link to={`/surface/aggregator/feature/${r.feature_idx}`} className="hover:underline">
                    {r.feature_idx}
                  </Link>
                </td>
                <td className="px-2 py-1.5 text-slate-200 truncate max-w-[220px]" title={r.label}>
                  {r.label || '—'}
                </td>
                <td className="px-2 py-1.5 text-slate-400 text-[11px]">{r.top_tissue || '—'}</td>
                <td className="px-2 py-1.5 text-slate-400 text-[11px]">{r.top_domain_l7 || '—'}</td>
                <td className="px-2 py-1.5 text-right text-slate-300 font-mono">
                  {fmt(r.morans_i_mean, 3)}
                </td>
                <td className="px-2 py-1.5 text-right text-slate-300 font-mono">
                  {fmt(r.proto_max_abs_cos, 3)}
                </td>
                <td className={`px-2 py-1.5 text-right font-mono ${depColor(r.dep_self_loop_norm)}`}>
                  {fmt(r.dep_self_loop_norm, 3)}
                </td>
                <td className={`px-2 py-1.5 text-right font-mono ${depColor(r.dep_random_rewire)}`}>
                  {fmt(r.dep_random_rewire, 3)}
                </td>
                <td className={`px-2 py-1.5 text-right font-mono ${ratioColor(r.tissue_max_ratio)}`}>
                  {fmt(r.tissue_max_ratio, 2)}
                </td>
                <td className={`px-2 py-1.5 text-right font-mono ${ratioColor(r.tech_max_ratio)}`}>
                  {fmt(r.tech_max_ratio, 2)}
                </td>
                <td className={`px-2 py-1.5 text-right font-mono ${ratioColor(r.slide_max_ratio)}`}>
                  {fmt(r.slide_max_ratio, 2)}
                </td>
                <td className={`px-2 py-1.5 text-right font-mono ${pctColor(r.proto_reassign_rate)}`}>
                  {pct(r.proto_reassign_rate)}
                </td>
                <td className={`px-2 py-1.5 text-right font-mono ${pctColor(r.l7_reassign_rate)}`}>
                  {pct(r.l7_reassign_rate)}
                </td>
                <td className="px-2 py-1.5 text-center">
                  {r.survives_all === true ? (
                    <span className="text-emerald-400 text-base">✓</span>
                  ) : r.survives_all === false ? (
                    <span className="text-slate-700">·</span>
                  ) : (
                    <span className="text-slate-700">—</span>
                  )}
                </td>
              </tr>
            ))}
          </tbody>
        </table>
      </div>

      {filteredRows.length > limit && (
        <div className="mt-4 flex justify-center">
          <button
            onClick={() => setLimit(limit + 100)}
            className="px-4 py-2 rounded-md bg-slate-800 hover:bg-slate-700 text-slate-200 text-xs transition"
          >
            show {Math.min(100, filteredRows.length - limit)} more
          </button>
        </div>
      )}

      <div className="mt-10 text-xs text-slate-500 leading-relaxed max-w-3xl">
        <strong className="text-slate-300">Column guide.</strong>{' '}
        <code>dep (norm)</code> is the degree-normalized contextual dependency from
        graph_ablation_v2 (how much feature activation collapses when the spatial graph is
        replaced with a 1/mean_degree-scaled self-loop; &gt; 0 means graph-dependent).
        <code className="mx-1">dep (rewire)</code> is the same statistic when the spatial
        graph is degree-preserving rewired. <code>tissue×</code>, <code>tech×</code>,
        <code>slide×</code> are max-class-share / baseline-share ratios from
        confounds_effect_size.parquet (≥ 2 means the top-1% cells pile on one class at 2×
        baseline frequency). <code>proto reassign</code> and <code>l7 reassign</code> come
        from the prototype_domain_ablation experiment (fraction of top cells whose SwAV
        prototype / l7 domain changes when the feature is ablated in the SAE code).{' '}
        <code>survives</code> is a per-feature boolean combining slide effect-size ≥ 2,
        tech-residualization survival, and l20-residualization survival.
      </div>
    </div>
  )
}

function HypothesisCard({ id, h }) {
  const verdict = h.verdict || 'PENDING'
  const color =
    verdict === 'CONFIRMED'
      ? 'emerald'
      : verdict === 'REFUTED'
        ? 'rose'
        : 'slate'
  const title = id
    .replace(/^H(\d+)_/, 'H$1 · ')
    .replace(/_/g, ' ')
  return (
    <div className="rounded-xl border border-slate-800 bg-slate-900/40 p-4">
      <div className="flex items-start justify-between gap-2 mb-2">
        <div className="text-sm font-semibold text-slate-100">{title}</div>
        <span
          className={`text-[10px] uppercase tracking-wider px-2 py-0.5 rounded ring-1 bg-${color}-500/10 text-${color}-300 ring-${color}-500/30`}
        >
          {verdict}
        </span>
      </div>
      <div className="text-[11px] text-slate-400 leading-snug mb-3">{h.claim}</div>
      <dl className="text-[11px] space-y-1">
        {Object.entries(h)
          .filter(([k]) => k !== 'claim' && k !== 'verdict' && k !== 'note')
          .map(([k, v]) => (
            <div key={k} className="flex justify-between gap-3">
              <dt className="text-slate-500 font-mono">{k}</dt>
              <dd className="text-slate-200 font-mono">{formatHypValue(v)}</dd>
            </div>
          ))}
      </dl>
      {h.note && (
        <div className="mt-2 text-[10px] text-amber-400/80 italic">note: {h.note}</div>
      )}
    </div>
  )
}

function formatHypValue(v) {
  if (v == null) return '—'
  if (typeof v === 'number') {
    if (Math.abs(v) < 1) return v.toFixed(4)
    return v.toFixed(2)
  }
  if (typeof v === 'boolean') return v ? 'yes' : 'no'
  return String(v)
}

function fmt(v, digits = 2) {
  if (v == null || Number.isNaN(v)) return '—'
  return Number(v).toFixed(digits)
}
function pct(v) {
  if (v == null || Number.isNaN(v)) return '—'
  return `${(Number(v) * 100).toFixed(0)}%`
}
function depColor(v) {
  if (v == null) return 'text-slate-500'
  if (v > 0.5) return 'text-emerald-400'
  if (v > 0.2) return 'text-emerald-500/70'
  if (v > -0.2) return 'text-slate-400'
  if (v > -1) return 'text-amber-400/80'
  return 'text-rose-400'
}
function ratioColor(v) {
  if (v == null) return 'text-slate-500'
  if (v >= 3) return 'text-rose-400'
  if (v >= 2) return 'text-amber-400'
  return 'text-slate-400'
}
function pctColor(v) {
  if (v == null) return 'text-slate-500'
  if (v >= 0.5) return 'text-emerald-400'
  if (v >= 0.2) return 'text-emerald-500/70'
  return 'text-slate-400'
}
