import { useEffect, useState } from 'react'
import { Link } from 'react-router-dom'
import { Loading, ErrorBox } from '../components/Loading.jsx'

// Cross-layer feature alignment / "information highways" page.
// Data: /data/hierarchical_composition.json + /data/depth_metrics.json
// (both generated by scripts/05_build_atlas_data.py or written directly)

const BASE = `${import.meta.env.BASE_URL}data`
const BUILD_ID = typeof __BUILD_ID__ !== 'undefined' ? __BUILD_ID__ : 'dev'

async function fetchJson(path) {
  const res = await fetch(`${BASE}${path}?v=${BUILD_ID}`, { cache: 'no-store' })
  if (!res.ok) throw new Error(`fetch ${path}: ${res.status}`)
  return res.json()
}

export default function LayerFlowPage() {
  const [comp, setComp] = useState(null)
  const [depth, setDepth] = useState(null)
  const [error, setError] = useState(null)

  useEffect(() => {
    Promise.all([
      fetchJson('/hierarchical_composition.json').catch(() => null),
      fetchJson('/depth_metrics.json').catch(() => null),
    ])
      .then(([c, d]) => {
        setComp(c)
        setDepth(d)
      })
      .catch(setError)
  }, [])

  if (error) return <ErrorBox error={error} />
  if (comp === null && depth === null) return <Loading what="layer flow data" />

  const adj = (comp || []).filter((r) => r.layer_gap === 1)
  const longRange = (comp || []).filter((r) => r.layer_gap > 1)

  return (
    <div>
      <div className="text-xs text-slate-500 mb-2">
        <Link to="/" className="hover:text-brand-300">Overview</Link> / Cross-layer flow
      </div>
      <h1 className="text-3xl font-bold text-slate-50 tracking-tight mb-2">
        Cross-layer feature flow
      </h1>
      <p className="text-slate-400 max-w-3xl leading-relaxed mb-8">
        How do SAE features at each GAT layer relate to the features at adjacent layers?
        H10 predicts that later-layer features progressively decompose into linear
        combinations of earlier-layer features. We measure this via pairwise cross-layer
        max absolute cosine similarity of SAE feature activations on 566K shared nodes.
      </p>

      {/* Depth metrics table */}
      {depth && depth.length > 0 && (
        <section className="mb-10">
          <h2 className="text-xl font-bold text-slate-100 mb-3">Per-layer summary</h2>
          <div className="overflow-x-auto rounded-lg border border-slate-800 bg-slate-900/40">
            <table className="w-full text-xs">
              <thead className="bg-slate-900 text-slate-400 uppercase text-[10px] tracking-wider">
                <tr>
                  <th className="text-left px-3 py-2">surface</th>
                  <th className="text-right px-3 py-2">var explained</th>
                  <th className="text-right px-3 py-2"># modules</th>
                  <th className="text-right px-3 py-2">alive %</th>
                  <th className="text-right px-3 py-2">tech confound %</th>
                  <th className="text-right px-3 py-2">superposition %</th>
                </tr>
              </thead>
              <tbody className="divide-y divide-slate-800">
                {depth.map((r) => (
                  <tr key={r.surface} className="hover:bg-slate-800/40 transition">
                    <td className="px-3 py-1.5 font-mono text-brand-300">
                      <Link to={`/surface/${r.surface}`} className="hover:underline">
                        {r.surface}
                      </Link>
                    </td>
                    <td className="px-3 py-1.5 text-right text-slate-200 font-mono">
                      {r.var_explained_full?.toFixed(4) ?? '—'}
                    </td>
                    <td className="px-3 py-1.5 text-right text-slate-300 font-mono">
                      {r.n_modules ?? '—'}
                    </td>
                    <td className="px-3 py-1.5 text-right text-slate-300 font-mono">
                      {r.alive_fraction != null ? (r.alive_fraction * 100).toFixed(0) + '%' : '—'}
                    </td>
                    <td className="px-3 py-1.5 text-right text-slate-300 font-mono">
                      {r.tech_confounded_fraction != null ? (r.tech_confounded_fraction * 100).toFixed(1) + '%' : '—'}
                    </td>
                    <td className="px-3 py-1.5 text-right text-slate-300 font-mono">
                      {r.fraction_non_aligned_svd != null ? (r.fraction_non_aligned_svd * 100).toFixed(1) + '%' : '—'}
                    </td>
                  </tr>
                ))}
              </tbody>
            </table>
          </div>
        </section>
      )}

      {/* Cross-layer alignment */}
      {adj.length > 0 && (
        <section className="mb-10">
          <h2 className="text-xl font-bold text-slate-100 mb-3">
            Adjacent-layer feature alignment (H10)
          </h2>
          <p className="text-slate-400 text-xs mb-4 max-w-2xl">
            For each target feature in layer L+1, we find the source feature in layer L with
            the highest absolute cosine similarity of activation patterns (on 566K shared nodes).
            The table shows summary statistics of the max-cosine distribution across target features.
          </p>
          <div className="overflow-x-auto rounded-lg border border-slate-800 bg-slate-900/40">
            <table className="w-full text-xs">
              <thead className="bg-slate-900 text-slate-400 uppercase text-[10px] tracking-wider">
                <tr>
                  <th className="text-left px-3 py-2">pair</th>
                  <th className="text-right px-3 py-2">mean max|cos|</th>
                  <th className="text-right px-3 py-2">median</th>
                  <th className="text-right px-3 py-2">p90</th>
                  <th className="text-right px-3 py-2">p95</th>
                  <th className="text-right px-3 py-2">frac &gt; 0.3</th>
                  <th className="text-right px-3 py-2">frac &gt; 0.5</th>
                </tr>
              </thead>
              <tbody className="divide-y divide-slate-800">
                {adj.map((r) => (
                  <tr key={`${r.source}-${r.target}`} className="hover:bg-slate-800/40 transition">
                    <td className="px-3 py-1.5 text-slate-200 font-mono text-[11px]">
                      {r.source} → {r.target}
                    </td>
                    <td className="px-3 py-1.5 text-right font-mono text-brand-300">
                      {r.max_abs_cos_mean?.toFixed(4)}
                    </td>
                    <td className="px-3 py-1.5 text-right font-mono text-slate-300">
                      {r.max_abs_cos_median?.toFixed(4)}
                    </td>
                    <td className="px-3 py-1.5 text-right font-mono text-slate-400">
                      {r.max_abs_cos_p90?.toFixed(4)}
                    </td>
                    <td className="px-3 py-1.5 text-right font-mono text-slate-400">
                      {r.max_abs_cos_p95?.toFixed(4)}
                    </td>
                    <td className="px-3 py-1.5 text-right font-mono text-slate-300">
                      {(r.frac_above_0_3 ?? r['frac_above_0.3'])?.toFixed(3) ?? '—'}
                    </td>
                    <td className="px-3 py-1.5 text-right font-mono text-slate-300">
                      {(r.frac_above_0_5 ?? r['frac_above_0.5'])?.toFixed(3) ?? '—'}
                    </td>
                  </tr>
                ))}
              </tbody>
            </table>
          </div>
          <div className="mt-4 text-xs text-slate-500 max-w-2xl">
            <strong className="text-slate-300">H10 trend:</strong> Mean max|cos| increases monotonically
            from 0.019 (conv_0→conv_1) to 0.055 (conv_8→conv_9), and frac &gt; 0.3 rises from 0.5%
            to 2.8%. Later GAT layers progressively compose earlier patterns, supporting H10.
            Absolute levels are low (~2–3% above cos 0.3) — consistent with H3 (superposition).
          </div>
        </section>
      )}

      {/* Long-range pairs */}
      {longRange.length > 0 && (
        <section className="mb-10">
          <h2 className="text-xl font-bold text-slate-100 mb-3">Long-range pairs</h2>
          <div className="overflow-x-auto rounded-lg border border-slate-800 bg-slate-900/40">
            <table className="w-full text-xs">
              <thead className="bg-slate-900 text-slate-400 uppercase text-[10px] tracking-wider">
                <tr>
                  <th className="text-left px-3 py-2">pair</th>
                  <th className="text-right px-3 py-2">gap</th>
                  <th className="text-right px-3 py-2">mean max|cos|</th>
                  <th className="text-right px-3 py-2">frac &gt; 0.3</th>
                  <th className="text-right px-3 py-2">frac &gt; 0.5</th>
                </tr>
              </thead>
              <tbody className="divide-y divide-slate-800">
                {longRange.map((r) => (
                  <tr key={`${r.source}-${r.target}`} className="hover:bg-slate-800/40 transition">
                    <td className="px-3 py-1.5 text-slate-200 font-mono text-[11px]">
                      {r.source} → {r.target}
                    </td>
                    <td className="px-3 py-1.5 text-right font-mono text-slate-400">
                      {r.layer_gap}
                    </td>
                    <td className="px-3 py-1.5 text-right font-mono text-brand-300">
                      {r.max_abs_cos_mean?.toFixed(4)}
                    </td>
                    <td className="px-3 py-1.5 text-right font-mono text-slate-300">
                      {(r.frac_above_0_3 ?? r['frac_above_0.3'])?.toFixed(3) ?? '—'}
                    </td>
                    <td className="px-3 py-1.5 text-right font-mono text-slate-300">
                      {(r.frac_above_0_5 ?? r['frac_above_0.5'])?.toFixed(3) ?? '—'}
                    </td>
                  </tr>
                ))}
              </tbody>
            </table>
          </div>
        </section>
      )}

      {!comp && (
        <div className="text-amber-400/80 text-sm">
          hierarchical_composition.json not yet generated. Run{' '}
          <code className="bg-slate-800 px-1 rounded text-xs">scripts/14_hierarchical_composition.py</code>
          {' '}and rebuild atlas data.
        </div>
      )}
    </div>
  )
}
